### ISSUE TITLE
Check exponentiation associativity

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/eel-wasm#30]
What does `2 ^ 2 ^ 4` resolve to?

**Comment by jberg** [comment]
I know you had a script to shows you function calls, does the `^` operator actually get used in presets? I know `pow` exists. I think `^` might only exist in the the cockos eel.

still a fun question regardless :D

**Comment by captbaritone** [comment]
Yeah, this was mostly just me being interested in understanding what's the difference between associativity and precedence as I read through my compiler text book :)

**Comment by jberg** [comment]
> Yeah, this was mostly just me being interested in understanding what's the difference between associativity and precedence as I read through my compiler text book :)

Yea, cool stuff. I should probably check how Im doing it currently hah
