### ISSUE TITLE
Infinite loops

### ISSUE THREAD

**Issue by jberg** [captbaritone/eel-wasm#36]
`loop` goes into an infinite loop with a fractional value:

https://eel.capt.dev/?globals=eyJmb28iOjAsInN1bSI6MH0%3D&eel=eCA9IDEuNTsKbG9vcCAoeCwKICBzdW0gPSBzdW0gKyAxOwopOyA%3D

```
x = 1.5;
loop (x,
  sum = sum + 1;
); 
```

also with zero:

https://eel.capt.dev/?globals=eyJmb28iOjAsInN1bSI6MH0%3D&eel=eCA9IDA7Cmxvb3AgKHgsCiAgc3VtID0gc3VtICsgMTsKKTsg

```
x = 0;
loop (x,
  sum = sum + 1;
); 
```

I need to do some tests in Milkdrop to see the proper way of handling these

**Comment by captbaritone** [comment]
I'm going to "assign" this to you @jberg just as a reminder to myself that the next step is for someone to try this out in Milkdrop. If I get caught up with other stuff and have time to look, I'll assign it back to myself.

**Comment by jberg** [comment]
OK. I did a bunch of tests.

The logic for `loop` is basically:

with `loop(x, ...)`

if `x < 1`: no-op
if `x > 1`: repeat Math.floor(x) times

![Screenshot 2020-10-14 235200](https://user-images.githubusercontent.com/428650/96378583-c9bbb300-1141-11eb-80e7-79587842f5d7.png)
![Screenshot 2020-10-14 235229](https://user-images.githubusercontent.com/428650/96378584-cc1e0d00-1141-11eb-85ec-db961cdc2deb.png)
![Screenshot 2020-10-14 235342](https://user-images.githubusercontent.com/428650/96378585-ccb6a380-1141-11eb-9742-66ba71ee6e9c.png)
![Screenshot 2020-10-14 235357](https://user-images.githubusercontent.com/428650/96378586-cd4f3a00-1141-11eb-836c-9725aa1a2ec3.png)
![Screenshot 2020-10-17 123431](https://user-images.githubusercontent.com/428650/96378591-d213ee00-1141-11eb-9bed-300c30c95b04.png)
![Screenshot 2020-10-17 123452](https://user-images.githubusercontent.com/428650/96378592-d2ac8480-1141-11eb-92ae-14e2cccffc87.png)
