### ISSUE TITLE
Allow presets to set preset version

### ISSUE THREAD

**Issue by jberg** [captbaritone/eel-wasm#38]
EEL2 is almost entirely additive to EEL1 presets. The only difference I know is in the handling of random variables, where EEL1 only returned integer values for `rand`.

We should allow `loadModule` to take a `version` (`1` or `2`), and then emit different bytecode for `rand` (and potentially any other differences we find, but I think its just `rand`)

**Comment by captbaritone** [comment]
What was the range for integer values returned by `rand` in EEL1?
