### ISSUE TITLE
sqrt of negative numbers

### ISSUE THREAD

**Issue by jberg** [captbaritone/eel-wasm#39]
Currently taking the `sqrt` of a negative number returns `NaN`, which makes sense: https://eel.capt.dev/?globals=eyJmb28iOjB9&eel=Zm9vID0gc3FydCgtMik%3D

In Butterchurn I preemptively take the absolute value of numbers before running them through `sqrt`

I will check in MilkDrop to see how its handled

**Comment by captbaritone** [comment]
Assigning to @jberg to investigate what Milkdrop does.

**Comment by jberg** [comment]
OK, I checked, and it seems like `sqrt(x)` = `sqrt(Math.abs(x))`:

![Screenshot 2020-10-14 235535](https://user-images.githubusercontent.com/428650/96378604-fe2f6f00-1141-11eb-8987-b842b8cff0cb.png)
![Screenshot 2020-10-14 235708](https://user-images.githubusercontent.com/428650/96378608-0091c900-1142-11eb-83f7-26240c87cb2b.png)

Ran through a bunch fo values for the 2nd one...probably should have looped, but I think its still conclusive
