### ISSUE TITLE
Debugging mode

### ISSUE THREAD

**Issue by jberg** [captbaritone/eel-wasm#40]
Somewhat related to: https://github.com/captbaritone/eel-wasm/issues/39

Spent a while tracking down a bug, which ended up being caused by a variable being set to `NaN`.

Wonder if it is worth adding some sort of debug mode where we throw or print when an eel variable gets set to `NaN`/`undefined`/`null` since thats never good hah

**Comment by captbaritone** [comment]
I wonder if the best way to do this would be to monkey patch the WebAssembly.Global objects that get passed into the application. If so, that would be easiest to do in the application itself. I think you would need to pass the authentic `Global`s into the WASM module and then wrap those in some other proxy object before passing them into your application.

**Comment by captbaritone** [comment]
Assigning to @jberg since I think this could be solved in "user land".

**Comment by jberg** [comment]
ahhh, that makes sense that I can just monkey patch it, good call! Thanks!
