### ISSUE TITLE
Incorrect handling of mod fractional numbers between 0 and 1

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/eel-wasm#54]
Test case that causes a trap: `g = 5 % 0.1;`

This preset triggers it: https://archive.org/details/md_suksma_ed_geining_hateops_flx_squeakers ([Webamp Link](https://webamp.org/?butterchurnPresetUrl=https://archive.org/cors/md_suksma_ed_geining_hateops_flx_squeakers/md_suksma_ed_geining_hateops_flx_squeakers.json))

<img width="1539" alt="Screen Shot 2021-04-12 at 4 07 04 PM" src="https://user-images.githubusercontent.com/162735/114503518-4bb50200-9be2-11eb-8f56-803bdceb2fba.png">

The error happens [here](https://github.com/captbaritone/eel-wasm/blob/3f7cb8115c31c769bfb0a563ec37f119c3781921/packages/compiler/src/wasmFunctions.ts#L66) but the source of the bug is that we check if the value of the right hand side of the `%` operator is zero _before_ we truncate it. Instead, we should truncate before testing.

Looking more closely, I am reminded that mod is broken in other subtle ways. The solution to this should probably be address #32 while ensuring that this bug gets fixed in the process.

**Comment by anakhu877** [comment]
https://github.com/captbaritone/eel-wasm/issues/54

**Comment by anakhu877** [comment]
- [ ] __

**Comment by anakhu877** [comment]
****
